// automatically generated by the FlatBuffers compiler, do not modify

package grpcexample

const (
	PhoneTypeMOBILE = 0
	PhoneTypeHOME = 1
	PhoneTypeWORK = 2
)

var EnumNamesPhoneType = map[int]string{
	PhoneTypeMOBILE:"MOBILE",
	PhoneTypeHOME:"HOME",
	PhoneTypeWORK:"WORK",
}

