// automatically generated by the FlatBuffers compiler, do not modify

package grpcexample

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PhoneNumber struct {
	_tab flatbuffers.Table
}

func GetRootAsPhoneNumber(buf []byte, offset flatbuffers.UOffsetT) *PhoneNumber {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PhoneNumber{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PhoneNumber) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PhoneNumber) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PhoneNumber) Number() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PhoneNumber) Ptype() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PhoneNumber) MutatePtype(n int8) bool {
	return rcv._tab.MutateInt8Slot(6, n)
}

func PhoneNumberStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PhoneNumberAddNumber(builder *flatbuffers.Builder, number flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(number), 0)
}
func PhoneNumberAddPtype(builder *flatbuffers.Builder, ptype int8) {
	builder.PrependInt8Slot(1, ptype, 0)
}
func PhoneNumberEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
